# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# automatically generated by gs-nodepkg
# please do not edit this file
#
# Original Author: Tastu Teche <tastuteche@yahoo.com>
# Purpose: support installation of nodejs packages from npmjs repo
#
# Bugs to tastuteche@yahoo.com
#
# @ECLASS: gs-nodepkg.eclass
#

inherit distutils-r1 g-sorcery
